apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: repository-validator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: repository-validator
    app.kubernetes.io/part-of: repository-validator
  name: repository-validator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: repository-validator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: repository-validator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/konflux-infra-tenant/repository-validator/repository-validator@sha256:dbdcacee4d09127b3f5707e1bd6791b233c1d3d92a4af19712b95d2b142e31bc
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
